# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9d7cd80800f2654dd24290d791ea8ee38d37915d5a4b5f2be5e037bd413933aec4c8ffeb34cc4803df3d2b3333c943c5b5ee4337fe76127ecf6bca0f52a657c

test:
  secret_key_base: a1bab35c4dcab6db2208ca4bdb8b8f21df121ade21a63cd9c8c50882357dae67f780cdaf0374d15c10d26582ad4fa7a6c50ef5617fa3e0c861ebeee5c20a1542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
