$(document).ready ->
  $('#mailing_address').click ->
    if $('#mailing_address').is(':checked')
      $('#title_order_buyers_attributes_0_mailing_address_attributes_street').val $('#title_order_property_attributes_street').val()
      $('#title_order_buyers_attributes_0_mailing_address_attributes_city').val $('#title_order_property_attributes_city').val()
      $('#title_order_buyers_attributes_0_mailing_address_attributes_state').val $('#title_order_property_attributes_state').val()
      $('#title_order_buyers_attributes_0_mailing_address_attributes_zip').val $('#title_order_property_attributes_zip').val()
    else
      $('#title_order_buyers_attributes_0_mailing_address_attributes_street').val ''
      $('#title_order_buyers_attributes_0_mailing_address_attributes_city').val ''
      $('#title_order_buyers_attributes_0_mailing_address_attributes_state').val ''
      $('#title_order_buyers_attributes_0_mailing_address_attributes_zip').val ''
    return
  return

# ---
# generated by js2coffee 2.2.0