$(document).ready ->
  $("input[id*='mailing_address_']").click ->
    number_of_buyers = $(event.target).attr('id').slice -1
    if $("#mailing_address_#{number_of_buyers}").is(":checked")
      $("#title_order_buyer_title_orders_attributes_#{number_of_buyers}_buyer_attributes_mailing_address_attributes_street").val $("#title_order_property_attributes_street").val()
      $("#title_order_buyer_title_orders_attributes_#{number_of_buyers}_buyer_attributes_mailing_address_attributes_city").val $("#title_order_property_attributes_city").val()
      $("#title_order_buyer_title_orders_attributes_#{number_of_buyers}_buyer_attributes_mailing_address_attributes_state").val $("#title_order_property_attributes_state").val()
      $("#title_order_buyer_title_orders_attributes_#{number_of_buyers}_buyer_attributes_mailing_address_attributes_zip").val $("#title_order_property_attributes_zip").val()
    else
      $("#title_order_buyer_title_orders_attributes_#{number_of_buyers}_buyer_attributes_mailing_address_attributes_street").val ""
      $("#title_order_buyer_title_orders_attributes_#{number_of_buyers}_buyer_attributes_mailing_address_attributes_city").val ""
      $("#title_order_buyer_title_orders_attributes_#{number_of_buyers}_buyer_attributes_mailing_address_attributes_state").val ""
      $("#title_order_buyer_title_orders_attributes_#{number_of_buyers}_buyer_attributes_mailing_address_attributes_zip").val ""
    return
  return;

# ---
# generated by js2coffee 2.2.0